### ISSUE TITLE
Cannot compile with recent boost (clang/gcc)

### ISSUE THREAD

**Issue by mpoquet** [3Hren/blackhole#186]
Hello,

I would like to improve the logs of some of my projects and blackhole looks like a very sexy candidate.

Unfortunately, I was not able to compile it on my machine, regardless of the branches and compiler combinations I tried :(. Is something wrong in the way I try to build blackhole?

### Build script
``` bash
#!/usr/bin/env bash
set -eux

rm -rf ./build
mkdir ./build && cd ./build
cmake ..
make
```

### Versions
- Boost 1.67.0-7
- gcc 8.2.0-2
- clang 6.0.1-2

### Build logs
[master-gcc.log](https://github.com/3Hren/blackhole/files/2333099/master-gcc.log): Looks like boost's API broke =/
[master-clang.log](https://github.com/3Hren/blackhole/files/2333098/master-clang.log): Looks like blackhole's code is not clang-compatible
[develop-gcc.log](https://github.com/3Hren/blackhole/files/2333097/develop-gcc.log), [develop-clang.log](https://github.com/3Hren/blackhole/files/2333096/develop-clang.log): Both compilers have trouble around `CHAR_WIDTH = 1;`

**Comment by 3Hren** [comment]
Hi!
Seems there is nothing wrong, just compilers and boost because backward incompatible :)

master-clang.log seems easy to fix, however, I currently have no c++ environment configured, so it takes time.

With boost I don't see a way how to fix it except the backward-compatibility can be activated somehow.

**Comment by Maturin** [comment]
I created PR #189 with a fix for this issue.
