### ISSUE TITLE
Document RTTI requirement

### ISSUE THREAD

**Issue by jpetso** [3Hren/blackhole#72]
One of the major shortcomings of Boost.Log is that it requires RTTI, even after adopting Boost.TypeIndex in 1.59.0. A quick grep in your repository shows that `dynamic_cast` is only used in a unit test and `typeid` is not used at all. However, it's hard to verify whether RTTI isn't pulled in from a different source, and whether disabling it would affect binary compatibility with the shared library part.

It would be great if the README spent a few words on documenting these things.

**Comment by 3Hren** [comment]
Hi!

Blackhole v0.5 uses RTTI for dynamic configuration.

That was one of the reasons because of which v1.0 came, so now there is no RTTI requirement.

Blackhole depends from: Boost.Thread, [rapidjson](https://github.com/miloyip/rapidjson) and [cppformat](https://github.com/cppformat/cppformat). AFAIK neither of them requires RTTI. But I'll check it more precisely and will add a notice in the README.

**Comment by jpetso** [comment]
Thanks!
