### ISSUE TITLE
Custom allocator for attributes

### ISSUE THREAD

**Issue by 3Hren** [3Hren/blackhole#76]
This is required to avoid ifdef shit like this: https://github.com/3Hren/blackhole/blob/master/include/blackhole/attributes.hpp#L7

This is easily doable with custom stack allocator with heap fallback: https://howardhinnant.github.io/stack_alloc.html

**Comment by 3Hren** [comment]
@antmat, @ijon, look.

Strong investigation with @antmat results in impossibility to inject stack allocator into the Standard Library transparently.

The reason is: when a vector is moved it reassigns its elements to the new allocator **only if there is another allocator provided in the move constructor**. While using move constructor overload without second parameter the library doesn't even check for equality of allocators assuming that if the types are same then they are equal. For stack allocators it's not true - they are always unequal.
There is `is_always_equal` trait that helps to optimize excess comparison, but it's not used. I think it's a logical bug in the STL.

However when the container knows about its stack allocator (`boost::small_vector` does) everything is okay.

Seems like we have to change nothing here.

**Comment by antmat** [comment]
Not really a bug in STL, as discussed. 
"the library doesn't even check for equality of allocators assuming that if the types are same then they are equal" - it don't check equality because it *moves* allocator, assuming that move constructed allocator is equal to allocator it was constructed from. It is required by standart containers for Allocator to meet requirements of Allocator - en.cppreference.com/w/cpp/concept/Allocator and by theese concepts if you copy an allocator it should be equal to copy(the same as you move it - it should be equal to allocator before move). As you said - it's not true for stack allocator, so we need to use external arena. BTW, maybe you could use an arena and hide it inside blackhole code.

**Comment by 3Hren** [comment]
> Not really a bug in STL, as discussed. 

I said it's a logical bug. Of course assuming that move constructed allocator is equal to allocator it was constructed from is a lie (you can just implement operator== that way that it will always return false no matter what).

> BTW, maybe you could use an arena and hide it inside blackhole code.

I can't, because it's the user responsibility to create containers. Blackhole can either borrow them or take an ownership.
Moreover small vector does it automatically without breaking the separation of concerns.
